In [27]:
import pandas as pd
from openpyxl import load_workbook

In [28]:
df = pd.read_excel('ReporteGeneralSpring2027.xls', skiprows=6)
print(f'Número de registros {len(df)}')

Número de registros 377

## Númnero de participantes reales activos

In [ ]:
mask_estudiantes_activos = df['Estatus Participante'] == "Activo"
perfiles_fake = ["EMILY PRUEBA PRUEBA PRUEBA", "Ashly Prueba"]
mask_perfiles_reales = ~(df['Nombre'].isin(perfiles_fake))

In [72]:
df_current_participantes =  df.loc[mask_estudiantes_activos & mask_perfiles_reales]
print(f"Número de participantes => {df_current_participantes.shape[0]}")

Número de participantes => 373

In [29]:
df.columns

Index(['ID', 'Foto Perfil', 'Unnamed: 2', 'Unnamed: 3', 'Traslado',
       'Unnamed: 5', 'Nombre', 'Unnamed: 7', 'Informacion vacuna', 'CI',
       'Telefono', 'Estatus Participante', 'Retirado motivo', 'Estatus visa',
       'Sponsor', 'Empleador', 'Posicion Laboral', 'Celular', 'Correo',
       'Clave', 'Calificacion Escrita', 'Exparticipante',
       'Comentario Pendiente', 'Precio', 'Cualitativa', 'Cuantitativa',
       'Medio', 'Nombre Amigo', 'Con quien vieja', 'Amigo Viaja',
       'Universidad', 'Carrera', 'Fecha Inicio Carrera', 'Fecha Final Carrera',
       'Entrevista', 'DS160', 'Tasa Consular', 'Ademdum', 'Fecha Inscripcion',
       'Prueba pagada', 'Pago Inscripcion', 'Pago Entrevista', 'Pago DS2019',
       'Aprobacion Inscripcion', 'Ciudad Domicilio', 'Direccion Domicilio',
       'Fecha Nacimiento', 'Semestre', 'Num materias',
       'Num participaciones forever', 'Cuenta convisa', 'Fecha emision visa',
       'Fecha expiracion visa', 'Visa turista', 'Visa mision turista',
       'Visa expiracion turista', 'Resultado psicometrico',
       'Tipo Envio Formulario visa', 'Tipo de plan'],
      dtype='object')

In [30]:
columnas_proceso = ['Nombre','Sponsor','Empleador', 'Posicion Laboral', 'Celular', 'Correo', 'Fecha Inscripcion', 'CI']

In [31]:
df['Estatus Participante'].unique()

array(['Activo', 'Retirado'], dtype=object)

In [32]:
df['Retirado motivo'].unique()

array(['Usuario retiro , motivo ',
       'Usuario retiro LeslieMancheno, motivo Retiro voluntario',
       'Usuario retiro Sheltoncarvalloj, motivo Retiro voluntario',
       'Usuario retiro Ashlyveliz, motivo Retiro voluntario'],
      dtype=object)

In [34]:
df.loc[mask_estudiantes_activos, columnas_proceso]

,Nombre,Sponsor,Empleador,Posicion Laboral,Celular,Correo,Fecha Inscripcion,CI
0,Oswaldo Josue Davila Medina,LIFETRAVELED,Loews Hotel,Houseperson,982646441,odavila@espol.edu.ec,2025-05-12,957594724
1,Gustavo David Banderas Najera,CHI,Evelyn Hill - NY,"Food Service, Gift Shop Worker, Maintenance",959208230,gustavobanderas76@gmail.com,2026-02-23,951743145
2,Brayner yasmany Bastidas guerrero,CHI,Penn Entertainment,Steward,994414014,bbastida@espol.edu.ec,2026-02-13,943130989
3,Juan Andres Quimis Barco,LIFETRAVELED,Loews Hotel,Food and Beverage,969813139,juan.andres.quimis1@gmail.com,2026-03-05,950251330
4,Belen Sahian Castro Mora,AAG,Big Cedar Lodge,Cook,988748350,belensahian05@gmail.com,2026-02-28,958412249
...,...,...,...,...,...,...,...,...
372,Danna Valeska Castillo Proano,AAG,Great Wolf Lodge Wisconsin,Lifeguard,958863773,dannvalesk@gmail.com,2026-05-07,955218383
373,Widinson Santiago Morán Delgado,CHI,Penn Entertainment,Guest Room Attendant,990319452,widinsonmorand15@gmail.com,2026-04-06,957483423
374,Sofia Isabela Munoz Tucunango,CHI,Extreme Pizza Myrtle Beach,Server,982084882,munoztsisabela@gmail.com,2026-04-28,930216452
375,Camila Adela Chalen Flores,GEC,"Diverse Concepts Dba, Pigeon Forge & Gatlinbur...",Ride Attendant,997419404,camila.adela.chalen@gmail.com,2026-05-05,931750897
376,ERICK SEBASTHIAN GUERRA GUTIERREZ,AAG,Great Wolf Lodge - Kansas City,Lifeguard,983255437,erickguerragutierrez@gmail.com,2026-03-11,930260633

In [35]:
df['Fecha Inscripcion'].dtype

dtype('<M8[ns]')

In [36]:
pd.Timestamp.now()

Timestamp('2026-05-10 14:04:47.373776')

In [37]:
pd.Timestamp.now() - pd.to_timedelta('1 day')

Timestamp('2026-05-09 14:04:47.380863')

In [38]:
yesterday = (pd.Timestamp.now() - pd.to_timedelta('1 day'))
yesterday.date()

datetime.date(2026, 5, 9)

In [39]:
mask_ultimos_chicos_inscritos = df['Fecha Inscripcion'] >= '2026-04-29'

In [40]:
df_ult_inscritos = df.loc[mask_estudiantes_activos & mask_ultimos_chicos_inscritos, columnas_proceso]

In [41]:
print(f'Participantes inscritos entre hoy y ayer => {len(df_ult_inscritos)}')

Participantes inscritos entre hoy y ayer => 70

In [42]:
df.loc[mask_ultimos_chicos_inscritos, ['Correo', 'Fecha Inscripcion']].sort_values(by='Fecha Inscripcion')

                                 Correo Fecha Inscripcion
207                gemilu.chg@gmail.com        2026-04-29
312           kevinalavabravo@gmail.com        2026-04-29
125               jamufrei@espol.edu.ec        2026-04-29
303          Williamdmoralesf@gmail.com        2026-04-29
119               alekex.3521@gmail.com        2026-04-29
..                                  ...               ...
204               marmmend@espol.edu.ec        2026-05-07
372                dannvalesk@gmail.com        2026-05-07
223              angelrugel34@gmail.com        2026-05-08
102  ortizbravoarianavaletina@gmail.com        2026-05-08
321            sara.quimi2020@gmail.com        2026-05-08

[71 rows x 2 columns]

In [43]:
yesterday.date()

datetime.date(2026, 5, 9)

In [44]:
yesterday = pd.Timestamp(yesterday).normalize()
yesterday

Timestamp('2026-05-09 00:00:00')

In [45]:
(df['Fecha Inscripcion'] == yesterday).sum()

np.int64(0)

In [46]:
(df['Fecha Inscripcion'] == '2026-05-04').sum()

np.int64(17)

In [47]:
mask_just_yesterday = df['Fecha Inscripcion'] == yesterday

In [48]:
print(f"Estudiantes inscritos el día de ayer {len(df.loc[mask_estudiantes_activos & mask_just_yesterday, columnas_proceso])}")

Estudiantes inscritos el día de ayer 0

In [49]:
participantes_inscritos_ayer = df.loc[mask_estudiantes_activos & mask_just_yesterday, columnas_proceso]
participantes_inscritos_ayer

Empty DataFrame
Columns: [Nombre, Sponsor, Empleador, Posicion Laboral, Celular, Correo, Fecha Inscripcion, CI]
Index: []

In [50]:
df.loc[mask_estudiantes_activos & mask_just_yesterday, ['Correo', 'Fecha Inscripcion']]

Empty DataFrame
Columns: [Correo, Fecha Inscripcion]
Index: []

In [51]:
# nombre_archivo = "Inscriptos_Spring2027_" + str_yesterday + ".xlsx"
# with pd.ExcelWriter(nombre_archivo) as writer:
#     participantes_inscritos_ayer.to_excel(writer)
# print("Excel guardado")

In [52]:
# wb = load_workbook(nombre_archivo)
# ws = wb.active


# for col in ws.columns:
#    max_lenght = max(len(str(cell.value)) for cell in col if cell.value)
#    ws.column_dimensions[col[0].column_letter].width = max_lenght + 2

# wb.save(nombre_archivo)

In [53]:
df['Entrevista'].unique()

array(['NO'], dtype=object)

In [54]:
str_yesterday = yesterday.strftime('%d-%m-%Y')
str_yesterday

'09-05-2026'

In [55]:
yesterday.day_name()

'Saturday'

In [56]:
df.columns

Index(['ID', 'Foto Perfil', 'Unnamed: 2', 'Unnamed: 3', 'Traslado',
       'Unnamed: 5', 'Nombre', 'Unnamed: 7', 'Informacion vacuna', 'CI',
       'Telefono', 'Estatus Participante', 'Retirado motivo', 'Estatus visa',
       'Sponsor', 'Empleador', 'Posicion Laboral', 'Celular', 'Correo',
       'Clave', 'Calificacion Escrita', 'Exparticipante',
       'Comentario Pendiente', 'Precio', 'Cualitativa', 'Cuantitativa',
       'Medio', 'Nombre Amigo', 'Con quien vieja', 'Amigo Viaja',
       'Universidad', 'Carrera', 'Fecha Inicio Carrera', 'Fecha Final Carrera',
       'Entrevista', 'DS160', 'Tasa Consular', 'Ademdum', 'Fecha Inscripcion',
       'Prueba pagada', 'Pago Inscripcion', 'Pago Entrevista', 'Pago DS2019',
       'Aprobacion Inscripcion', 'Ciudad Domicilio', 'Direccion Domicilio',
       'Fecha Nacimiento', 'Semestre', 'Num materias',
       'Num participaciones forever', 'Cuenta convisa', 'Fecha emision visa',
       'Fecha expiracion visa', 'Visa turista', 'Visa mision turista',
       'Visa expiracion turista', 'Resultado psicometrico',
       'Tipo Envio Formulario visa', 'Tipo de plan'],
      dtype='object')

In [57]:
mask_prueba_ingles_escrita = df['Calificacion Escrita'] == 'Sin Calificacion'

In [58]:
pd.Timestamp(pd.Timestamp.now().date())

Timestamp('2026-05-10 00:00:00')

In [59]:
mask_fecha_corte = df['Fecha Inscripcion'] < pd.Timestamp(pd.Timestamp.now().date())

In [60]:
mask_fecha_corte.sum()

np.int64(377)

Tengo que ver y filtar un grupo por los inscritos en los ultimos 3 días
y lo que se han inscritos hace más de 3 días y no han firmado contrato

# PRUEBA INGLES ESCRITA

In [61]:
df_sin_prueba_ingles_escrita = df.loc[mask_estudiantes_activos & mask_prueba_ingles_escrita & mask_fecha_corte, columnas_proceso]
df_sin_prueba_ingles_escrita

,Nombre,Sponsor,Empleador,Posicion Laboral,Celular,Correo,Fecha Inscripcion,CI
15,Romina Maite Mendoza Garofalo,PENDIENTE POR DESTINO,PENDIENTE POR DESTINO,PENDIENTE POR DESTINO,986699791,rominammg2020@gmail.com,2026-03-26,606230092
18,Oscar Joshua Arevalo Villacrés,AAG,Great Wolf Lodge Wisconsin,Room Attendant,939446758,oscartarzan12@gmail.com,2026-04-28,954011730
20,Sebastian Diego Mata Vacacela,LIFETRAVELED,Anderson’s swim School,Lifeguard / Swim Instructor,958880858,sebastianmatav3@gmail.com,2026-04-13,930449475
23,Suleimy Gisell Damian Macias,CHI,Northwest X Southern Hospitality LLC,Room Attendant,997694728,suleimyd962@gmail.com,2026-05-05,1722719837
37,Emily Fiorella Quimi Manners,SPIRIT,WILDERNESS TENNESSEE,Food and beverage,960181799,emilyfiorellaquimimanners@gmail.com,2026-04-24,955603865
...,...,...,...,...,...,...,...,...
357,Bianca Solange Cheme Varas,CHI,GRAND PRIX,Admissions,985482991,bianca.cheme.liceo@gmail.com,2026-05-06,929650224
360,ROSA ANDREA SANCHEZ VELASQUEZ,CHI,"AUDUBON ZOO, NEW ORLEANS, LA",Busser/Dishwasher,993548982,rosasanchez242004@gmail.com,2026-05-05,958472003
361,Andrea Viviana Arevalo Villacres,AAG,Great Wolf Lodge Wisconsin,Lifeguard,988522730,andrarev@espol.edu.ec,2026-04-29,954011581
362,Domenica Raquel De La Cruz Quinde,AAG,Margaritaville Lake Resort Lake of the Ozarks,Hotel resort worker,5737461831,domedq2003@gmail.com,2026-04-30,959007295
375,Camila Adela Chalen Flores,GEC,"Diverse Concepts Dba, Pigeon Forge & Gatlinbur...",Ride Attendant,997419404,camila.adela.chalen@gmail.com,2026-05-05,931750897

In [62]:
print(f'Participantes sin prueba de inglés escrita=> {len(df_sin_prueba_ingles_escrita)}')

Participantes sin prueba de inglés escrita=> 96

In [63]:
df.columns

Index(['ID', 'Foto Perfil', 'Unnamed: 2', 'Unnamed: 3', 'Traslado',
       'Unnamed: 5', 'Nombre', 'Unnamed: 7', 'Informacion vacuna', 'CI',
       'Telefono', 'Estatus Participante', 'Retirado motivo', 'Estatus visa',
       'Sponsor', 'Empleador', 'Posicion Laboral', 'Celular', 'Correo',
       'Clave', 'Calificacion Escrita', 'Exparticipante',
       'Comentario Pendiente', 'Precio', 'Cualitativa', 'Cuantitativa',
       'Medio', 'Nombre Amigo', 'Con quien vieja', 'Amigo Viaja',
       'Universidad', 'Carrera', 'Fecha Inicio Carrera', 'Fecha Final Carrera',
       'Entrevista', 'DS160', 'Tasa Consular', 'Ademdum', 'Fecha Inscripcion',
       'Prueba pagada', 'Pago Inscripcion', 'Pago Entrevista', 'Pago DS2019',
       'Aprobacion Inscripcion', 'Ciudad Domicilio', 'Direccion Domicilio',
       'Fecha Nacimiento', 'Semestre', 'Num materias',
       'Num participaciones forever', 'Cuenta convisa', 'Fecha emision visa',
       'Fecha expiracion visa', 'Visa turista', 'Visa mision turista',
       'Visa expiracion turista', 'Resultado psicometrico',
       'Tipo Envio Formulario visa', 'Tipo de plan'],
      dtype='object')

In [64]:
df['Precio']

0             Usuario Actualizo admin - Precio - 1599.00
1      Usuario Actualizo RECEPCIONUIO - Precio - 1599.00
2      Usuario Actualizo RECEPCIONUIO - Precio - 1699.00
3      Usuario Actualizo Melissagomez - Precio - 1650.00
4      Usuario Actualizo RECEPCIONUIO - Precio - 1599.00
                             ...
372    Usuario Actualizo LeslieMancheno - Precio - 17...
373    Usuario Actualizo Melissagomez - Precio - 1599.00
374    Usuario Actualizo RominaLeonCarpio - Precio - ...
375    Usuario Actualizo KarenUrbinaO - Precio - 1699.00
376    Usuario Actualizo RECEPCIONUIO - Precio - 1650.00
Name: Precio, Length: 377, dtype: object

In [65]:
mask_precio_no_capturado = df['Precio'].str.split(' ').str[-1].astype('float') == 0

In [66]:
df_precios_no_capturados = df.loc[mask_estudiantes_activos & mask_precio_no_capturado, columnas_proceso]
print(f"Participantes sin precio capturado => {len(df_precios_no_capturados)}")

Participantes sin precio capturado => 1

In [67]:
df_precios_no_capturados   # Porque me sale Emily Prueba prueba?

,Nombre,Sponsor,Empleador,Posicion Laboral,Celular,Correo,Fecha Inscripcion,CI
189,EMILY PRUEBA PRUEBA PRUEBA,AAG,Big Cedar Lodge,Back of the house,975553125,emilyvaleriag02@gmail.com,2026-03-19,958569907

In [68]:
df.columns

Index(['ID', 'Foto Perfil', 'Unnamed: 2', 'Unnamed: 3', 'Traslado',
       'Unnamed: 5', 'Nombre', 'Unnamed: 7', 'Informacion vacuna', 'CI',
       'Telefono', 'Estatus Participante', 'Retirado motivo', 'Estatus visa',
       'Sponsor', 'Empleador', 'Posicion Laboral', 'Celular', 'Correo',
       'Clave', 'Calificacion Escrita', 'Exparticipante',
       'Comentario Pendiente', 'Precio', 'Cualitativa', 'Cuantitativa',
       'Medio', 'Nombre Amigo', 'Con quien vieja', 'Amigo Viaja',
       'Universidad', 'Carrera', 'Fecha Inicio Carrera', 'Fecha Final Carrera',
       'Entrevista', 'DS160', 'Tasa Consular', 'Ademdum', 'Fecha Inscripcion',
       'Prueba pagada', 'Pago Inscripcion', 'Pago Entrevista', 'Pago DS2019',
       'Aprobacion Inscripcion', 'Ciudad Domicilio', 'Direccion Domicilio',
       'Fecha Nacimiento', 'Semestre', 'Num materias',
       'Num participaciones forever', 'Cuenta convisa', 'Fecha emision visa',
       'Fecha expiracion visa', 'Visa turista', 'Visa mision turista',
       'Visa expiracion turista', 'Resultado psicometrico',
       'Tipo Envio Formulario visa', 'Tipo de plan'],
      dtype='object')