In [217]:
import pandas as pd
from openpyxl import load_workbook

In [218]:
df = pd.read_excel('ReporteGeneralSpring2027.xls', skiprows=6)
print(f'Número de registros {len(df)}')

Número de registros 435

In [219]:
columnas_proceso = ['CI', 'Celular','Nombre','Sponsor','Empleador', 'Posicion Laboral', 'Correo', 'Fecha Inscripcion', 'Precio']

In [220]:
df['Retirado motivo'].unique()

array(['Usuario retiro , motivo ',
       'Usuario retiro LeslieMancheno, motivo Retiro voluntario',
       'Usuario retiro Sheltoncarvalloj, motivo Retiro voluntario',
       'Usuario retiro Ashlyveliz, motivo Retiro voluntario'],
      dtype=object)

In [221]:
df['Nombre'] = df["Nombre"].str.strip().str.lower()

# Pacticipantes **Reales**  y **Activos**

In [222]:
mask_estudiantes_activos = df['Estatus Participante'] == "Activo"
mask_no_prueba = ~(df['Nombre'].str.contains('prueba'))
perfiles_fake = ["veronica alejandra ollage velastegí", "camila prueba", "emily prueba prueba prueba", "ashly prueba"]
mask_perfiles_reales = ~(df['Nombre'].isin(perfiles_fake))

In [223]:
df_activos  = df.loc[mask_estudiantes_activos & mask_perfiles_reales & mask_no_prueba]
print(f"Participantes activos => {len(df_activos)}")

Participantes activos => 428

# PRUEBA INGLES ESCRITA

In [224]:
sin_prueba_escrita = df_activos['Calificacion Escrita'] == 'Sin Calificacion'
con_prueba_escrita = df_activos['Calificacion Escrita'] != 'Sin Calificacion'
print(f"Activos => {len(df_activos)}")
print(f'Participantes SIN prueba de inglés escrita => {sin_prueba_escrita.sum()}')
print(f'Participantes CON prueba de inglés escrita => {con_prueba_escrita.sum()}')
print(f'Cuadre pruebas => {sin_prueba_escrita.sum() + con_prueba_escrita.sum()}')

Activos => 428
Participantes SIN prueba de inglés escrita => 122
Participantes CON prueba de inglés escrita => 306
Cuadre pruebas => 428

# PRUEBA DE INGLES ORAL

In [225]:
sin_prueba_oral = df_activos['Cualitativa'] == "Sin Nota"
con_prueba_oral = df_activos['Cualitativa'] != "Sin Nota"
print(f"Activos => {len(df_activos)}")
print(f'Participantes SIN prueba de inglés oral => {sin_prueba_oral.sum()}')
print(f'Participantes CON prueba de inglés oral => {con_prueba_oral.sum()}')
print(f'Cuadre pruebas => {sin_prueba_oral.sum() + con_prueba_oral.sum()}')

Activos => 428
Participantes SIN prueba de inglés oral => 250
Participantes CON prueba de inglés oral => 178
Cuadre pruebas => 428

# Sin capturar precio

In [226]:
mask_precio_no_capturado = df_activos['Precio'].str.split(' ').str[-1].astype('float') == 0
df_precios_no_capturados = df_activos.loc[mask_estudiantes_activos & mask_precio_no_capturado, columnas_proceso].sort_values(by='Fecha Inscripcion')
print(f"Participantes sin precio capturado => {len(df_precios_no_capturados)}")

Participantes sin precio capturado => 18

In [227]:
df_precios_no_capturados

,CI,Celular,Nombre,Sponsor,Empleador,Posicion Laboral,Correo,Fecha Inscripcion,Precio
103,1316103306,963941584,carlos jonaiker pazmino bazurto,PENDIENTE POR DESTINO,PENDIENTE POR DESTINO,PENDIENTE POR DESTINO,carlosjonaiker345@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
380,957773203,939306701,derlis ezequiel mejillones bazurto,CHI,LCP Cupples - Westin St. Louis,Houseperson,derlismejillonesb@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
364,942436189,959206524,ailyn dayanna herrera sánchez,SPIRIT,THE HANGOUT,Busser,ailynherrerasanchez2728@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
348,955807821,982726339,tiffany jazmín vera jara,CHI,Hilton Waikoloa Village - Hawai,Room attendant (mujeres),Tiffanyvera2006@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
300,952052561,996617431,naomi lilibeth espinoza hualpa,AAG,Kalahari Resort - Wisconsin Dells,Food and Beverage Retail Concessions,naoespinoza2006@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
294,943528216,979508297,willy alexander soledispa valverde,CHI,"AUDUBON ZOO, NEW ORLEANS, LA",Food and Beverage Associate,Willysoledispapompeya@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
274,931382816,962869660,maria paula moya kittyle,GEC,"Diverse Concepts Dba, Pigeon Forge & Gatlinbur...",Cook,mpaulamoyak@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
388,955572706,968461590,erick roberto oviedo freire,CHI,Hilton Waikoloa Village - Hawai,Room attendant (hombres),erick.oviedof@hotmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
267,955773635,961246452,ernesto alonso suco toledo,CHI,Bojangles,Team Member,Eralsuco@espol.edu.ec,2026-05-15,Usuario Actualizo - Precio - 0.00
232,956126924,988591001,daniela romina quinteros reinoso,PENDIENTE POR DESTINO,PENDIENTE POR DESTINO,PENDIENTE POR DESTINO,danielaquinteros431@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
216,951606037,964104060,jorge santiago silva sierra,AAG,Food Lion Nags Head NC,Retail Associate,Jorgessilvas26@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
192,957975352,987159948,xavier giovanny peñaherrera delgado,CHI,Hilton Waikoloa Village - Hawai,Room attendant (hombres),xavierpd12@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
145,952622827,997380774,elio sebastian quimis medina,AAG,Food Lion Nags Head NC,Retail Associate,eliosebasqm@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
137,955861190,984028934,gabriel enrique narvaez saavedra,AAG,Kalahari Resort - Pocono Mountains PA,Restaurant Attendant,gabrielnarvaez0409@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
116,956331797,986398721,tiffany carolina lainez borbor,AAG,Mt. Olympus,Room Attendant,tlainez2005@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
240,950965616,962982162,carlos enrique zambrano baquerizo,AAG,Kalahari Resort - Wisconsin Dells,Waterpark Attendant,orestezambrano14@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
409,953816600,968630230,alejandro bernabe veliz urgiles,SPIRIT,MT. OLYMPUS,Flex AM,24alejandrovu@gmail.com,2026-05-15,Usuario Actualizo - Precio - 0.00
295,931975585,983040374,david xavier campuzano urgilés,SPIRIT,MT. OLYMPUS,Flex AM,campuzanodavid653@gmail.com,2026-05-16,Usuario Actualizo - Precio - 0.00

# Parcticipantes inscritos el día de ayer

In [228]:
yesterday = (pd.Timestamp.now() - pd.to_timedelta('1 day'))
yesterday.date()

datetime.date(2026, 5, 16)

In [229]:
yesterday = pd.Timestamp(yesterday).normalize()
yesterday

Timestamp('2026-05-16 00:00:00')

In [230]:
mask_just_yesterday = df['Fecha Inscripcion'] == yesterday

In [231]:
print(f"Estudiantes inscritos el día de ayer {len(df.loc[mask_estudiantes_activos & mask_just_yesterday, columnas_proceso])}")

Estudiantes inscritos el día de ayer 1

In [232]:
participantes_inscritos_ayer = df_activos.loc[mask_estudiantes_activos & mask_perfiles_reales & mask_just_yesterday, columnas_proceso]
participantes_inscritos_ayer

,CI,Celular,Nombre,Sponsor,Empleador,Posicion Laboral,Correo,Fecha Inscripcion,Precio
295,931975585,983040374,david xavier campuzano urgilés,SPIRIT,MT. OLYMPUS,Flex AM,campuzanodavid653@gmail.com,2026-05-16,Usuario Actualizo - Precio - 0.00

In [233]:
str_yesterday = yesterday.strftime('%d-%m-%Y')
str_yesterday

'16-05-2026'

In [234]:
nombre_archivo = "Inscriptos_Spring2027_" + str_yesterday + ".xlsx"
with pd.ExcelWriter(nombre_archivo) as writer:
    participantes_inscritos_ayer.to_excel(writer)
print("Excel guardado")

Excel guardado

In [235]:
wb = load_workbook(nombre_archivo)
ws = wb.active


for col in ws.columns:
   max_lenght = max(len(str(cell.value)) for cell in col if cell.value)
   ws.column_dimensions[col[0].column_letter].width = max_lenght + 2

wb.save(nombre_archivo)

In [236]:
df['Entrevista'].unique()

array(['NO'], dtype=object)

In [237]:
pd.Timestamp(pd.Timestamp.now().date())

Timestamp('2026-05-17 00:00:00')

In [238]:
mask_fecha_corte = df['Fecha Inscripcion'] < pd.Timestamp(pd.Timestamp.now().date())

In [239]:
mask_fecha_corte.sum()

np.int64(435)

Tengo que ver y filtar un grupo por los inscritos en los ultimos 3 días
y lo que se han inscritos hace más de 3 días y no han firmado contrato

# SIN FIRMA DE CONTRATO DESGLOSE

In [240]:
df_sin_firma = pd.read_excel("SinFirmarContratro.xls", skiprows=6)
print("Excel sin firma contrato cargado")
df_sin_firma['Nombre'] = df_sin_firma['Nombre'].str.strip().str.lower()

mask_no_prueba = ~(df_sin_firma['Nombre'].str.contains('prueba'))
mask_perfiles_reales_sin_contrato = ~(df_sin_firma['Nombre'].isin(perfiles_fake))
mask_sin_firma_activos  = df_sin_firma['Estatus Participante'] != "Retirado"


df_sin_firma = df_sin_firma.loc[mask_perfiles_reales_sin_contrato & mask_sin_firma_activos & mask_no_prueba, columnas_proceso]
df_sin_firma['Fecha Inscripcion'].dt.month_name().value_counts()

Excel sin firma contrato cargado

Fecha Inscripcion
May      44
April     1
March     1
Name: count, dtype: int64

In [241]:
len(df_sin_firma)

46

# Prueba agendadas

In [269]:
df_pruebas = pd.read_excel('Reporte prueba ingles.xlsx', skiprows=1)
df_pruebas['Nombre'] = df_pruebas['Nombre'].str.lower()

mask_pruebas_activos =  df_pruebas['Estatus Participante'] != "Retirado"
mask_pruebas_no_fake = ~(df_pruebas['Nombre'].isin(perfiles_fake))
mask_no_prueba = ~(df_pruebas['Nombre'].str.contains('prueba'))

df_pruebas = df_pruebas.loc[mask_pruebas_activos & mask_pruebas_no_fake & mask_no_prueba]
print(len(df_pruebas))

437

In [273]:
mask_sin_note = df_pruebas['Cualitativa'] == "Sin Nota"
mask_sin_fecha = df_pruebas['Fecha agenda prueba'] == '\xa0'
mask_con_nota = df_pruebas['Cualitativa'] != "Sin Nota"

In [274]:
df_pruebas.loc[mask_sin_note & ~mask_sin_fecha].shape # Pruebas Agendadas

(135, 15)

In [275]:
df_pruebas.loc[mask_sin_fecha].shape # Sin prueba agendada (Algunos tiene nota D:)

(132, 15)

In [276]:
df_pruebas.loc[mask_con_nota & ~mask_sin_fecha].shape

(170, 15)